create schema if not exists extensions;

create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_net with schema extensions;
create extension if not exists pg_cron with schema extensions;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.get_app_secret(secret_name text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  secret_value text;
begin
  select decrypted_secret
  into secret_value
  from vault.decrypted_secrets
  where name = secret_name
  limit 1;

  if secret_value is null then
    raise exception 'missing app secret: %', secret_name;
  end if;

  return secret_value;
end;
$$;

revoke all on function public.get_app_secret(text) from public;
revoke all on function public.get_app_secret(text) from anon;
revoke all on function public.get_app_secret(text) from authenticated;
grant execute on function public.get_app_secret(text) to service_role;

do $$
declare
  current_secret_id uuid;
begin
  select id into current_secret_id from vault.decrypted_secrets where name = 'project_url' limit 1;
  if current_secret_id is null then
    perform vault.create_secret('https://ssywkystkkixujhuantf.supabase.co', 'project_url', 'Supabase project URL for LocalYodis push jobs');
  else
    perform vault.update_secret(current_secret_id, 'https://ssywkystkkixujhuantf.supabase.co', 'project_url', 'Supabase project URL for LocalYodis push jobs');
  end if;

  select id into current_secret_id from vault.decrypted_secrets where name = 'supabase_anon_key' limit 1;
  if current_secret_id is null then
    perform vault.create_secret('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzeXdreXN0a2tpeHVqaHVhbnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5Nzc3MjEsImV4cCI6MjA4ODU1MzcyMX0.irgwW8PidC8VQdntRuG_mNDFb0iDIO8_c0iFl-kCyV4', 'supabase_anon_key', 'Legacy anon key used by pg_cron to invoke push dispatch');
  else
    perform vault.update_secret(current_secret_id, 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzeXdreXN0a2tpeHVqaHVhbnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5Nzc3MjEsImV4cCI6MjA4ODU1MzcyMX0.irgwW8PidC8VQdntRuG_mNDFb0iDIO8_c0iFl-kCyV4', 'supabase_anon_key', 'Legacy anon key used by pg_cron to invoke push dispatch');
  end if;

  select id into current_secret_id from vault.decrypted_secrets where name = 'rss_server_base_url' limit 1;
  if current_secret_id is null then
    perform vault.create_secret('https://localyodisserver.vercel.app', 'rss_server_base_url', 'RSS aggregation backend for LocalYodis');
  else
    perform vault.update_secret(current_secret_id, 'https://localyodisserver.vercel.app', 'rss_server_base_url', 'RSS aggregation backend for LocalYodis');
  end if;
end;
$$;

create table if not exists public.push_devices (
  device_id text primary key,
  endpoint text not null unique,
  subscription jsonb not null,
  permission text not null default 'default',
  user_agent text,
  locale text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  disabled_at timestamptz
);

create table if not exists public.push_source_preferences (
  device_id text not null references public.push_devices(device_id) on delete cascade,
  source_url text not null,
  source_name text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (device_id, source_url)
);

create index if not exists push_source_preferences_enabled_source_idx
  on public.push_source_preferences (source_url)
  where enabled = true;

create table if not exists public.push_source_state (
  source_url text primary key,
  last_item_key text,
  last_item_title text,
  last_item_link text,
  last_item_published_at timestamptz,
  checked_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.push_deliveries (
  id bigint generated by default as identity primary key,
  device_id text not null references public.push_devices(device_id) on delete cascade,
  source_url text not null,
  item_key text not null,
  item_title text,
  item_link text,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  response_status integer,
  error_message text,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  unique (device_id, source_url, item_key)
);

create index if not exists push_deliveries_source_item_idx
  on public.push_deliveries (source_url, item_key);

drop trigger if exists push_devices_set_updated_at on public.push_devices;
create trigger push_devices_set_updated_at
before update on public.push_devices
for each row
execute function public.set_updated_at();

drop trigger if exists push_source_preferences_set_updated_at on public.push_source_preferences;
create trigger push_source_preferences_set_updated_at
before update on public.push_source_preferences
for each row
execute function public.set_updated_at();

drop trigger if exists push_source_state_set_updated_at on public.push_source_state;
create trigger push_source_state_set_updated_at
before update on public.push_source_state
for each row
execute function public.set_updated_at();

alter table public.push_devices enable row level security;
alter table public.push_source_preferences enable row level security;
alter table public.push_source_state enable row level security;
alter table public.push_deliveries enable row level security;

select cron.unschedule(jobid)
from cron.job
where jobname = 'dispatch-push-notifications';

select
  cron.schedule(
    'dispatch-push-notifications',
    '*/5 * * * *',
    $$
    select
      net.http_post(
        url := public.get_app_secret('project_url') || '/functions/v1/push-dispatch',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', 'Bearer ' || public.get_app_secret('supabase_anon_key')
        ),
        body := jsonb_build_object('trigger', 'cron')
      );
    $$
  );
