#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run test
TEST_STATUS=$?

if [ $TEST_STATUS -ne 0 ]; then
  echo "Tests failed. Aborting push."
  exit $TEST_STATUS
fi

npm run build
BUILD_STATUS=$?

if [ $BUILD_STATUS -ne 0 ]; then
  echo "Build failed. Aborting push."
  exit $BUILD_STATUS
fi
